<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="apples-MacBook-Air.local" ignored="4" name="Default test(failed)(failed)" tests="2" failures="1" timestamp="2022-10-20T07:30:17 IST" time="15.053" errors="0">
  <testcase name="verifyLoginLogoTest" time="0.103" classname="TestCases.FailedTest"/>
  <testcase name="verifyBotLogoTest" time="0.077" classname="TestCases.FailedTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.verifyBotLogoTest(FailedTest.java:39)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyBotLogoTest -->
  <testcase name="verifyUrlTest" time="0.0" classname="TestCases.FailedTest">
    <ignored/>
  </testcase> <!-- verifyUrlTest -->
  <testcase name="loginToApp1Test" time="0.0" classname="TestCases.FailedTest">
    <ignored/>
  </testcase> <!-- loginToApp1Test -->
  <testcase name="verifyTitleTest" time="0.0" classname="TestCases.FailedTest">
    <ignored/>
  </testcase> <!-- verifyTitleTest -->
  <testcase name="loginToApp2Test" time="0.0" classname="TestCases.FailedTest">
    <ignored/>
  </testcase> <!-- loginToApp2Test -->
</testsuite> <!-- Default test(failed)(failed) -->
